server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://umc-serverstudy.c4c6drbqdp7s.ap-northeast-2.rds.amazonaws.com :3306/Week7?autoReconnect=true
    username: taehyun
    password: xogus921
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
#    driver-class-name: com.mysql.jdbc.Driver # mysql 5버전